[package]
name = "rocky28447/silo"
description = "State container class"
version = "0.4.1"
license = "MIT"
authors = ["Stephen Leitnick"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
